export default {
  Headline: {
    EffectiveDate: "2022-03-23T19:00:00+02:00",
    EffectiveEpochDate: 1648054800,
    Severity: 3,
    Text: "Expect rainy weather Wednesday evening through Thursday evening",
    Category: "rain",
    EndDate: "2022-03-25T01:00:00+02:00",
    EndEpochDate: 1648162800,
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?unit=c&lang=en-us",
  },
  DailyForecasts: [
    {
      Date: "2022-03-22T07:00:00+02:00",
      EpochDate: 1647925200,
      Sun: {
        Rise: "2022-03-22T05:43:00+02:00",
        EpochRise: 1647920580,
        Set: "2022-03-22T17:54:00+02:00",
        EpochSet: 1647964440,
      },
      Moon: {
        Rise: "2022-03-22T22:30:00+02:00",
        EpochRise: 1647981000,
        Set: "2022-03-23T08:57:00+02:00",
        EpochSet: 1648018620,
        Phase: "WaningGibbous",
        Age: 20,
      },
      Temperature: {
        Minimum: {
          Value: 9.5,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 14.8,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 8.7,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 18.2,
          Unit: "C",
          UnitType: 17,
          Phrase: "Pleasant",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 8.7,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 14.3,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      HoursOfSun: 8.0,
      DegreeDaySummary: {
        Heating: {
          Value: 6.0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 0.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 7,
          Category: "High",
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 3,
        IconPhrase: "Partly sunny",
        HasPrecipitation: false,
        ShortPhrase: "Turning sunny and cool",
        LongPhrase: "Cool with some clouds, then sunshine",
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 11.1,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 357,
            Localized: "N",
            English: "N",
          },
        },
        WindGust: {
          Speed: {
            Value: 31.5,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 333,
            Localized: "NNW",
            English: "NNW",
          },
        },
        TotalLiquid: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 29,
        Evapotranspiration: {
          Value: 3.0,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 11908.7,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: "Partly cloudy",
        HasPrecipitation: false,
        ShortPhrase: "Partly cloudy",
        LongPhrase: "Partly cloudy",
        PrecipitationProbability: 24,
        ThunderstormProbability: 0,
        RainProbability: 24,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 94,
            Localized: "E",
            English: "E",
          },
        },
        WindGust: {
          Speed: {
            Value: 22.2,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 354,
            Localized: "N",
            English: "N",
          },
        },
        TotalLiquid: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 30,
        Evapotranspiration: {
          Value: 0.5,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0.0,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=1&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=1&unit=c&lang=en-us",
    },
    {
      Date: "2022-03-23T07:00:00+02:00",
      EpochDate: 1648011600,
      Sun: {
        Rise: "2022-03-23T05:42:00+02:00",
        EpochRise: 1648006920,
        Set: "2022-03-23T17:54:00+02:00",
        EpochSet: 1648050840,
      },
      Moon: {
        Rise: "2022-03-23T23:40:00+02:00",
        EpochRise: 1648071600,
        Set: "2022-03-24T09:47:00+02:00",
        EpochSet: 1648108020,
        Phase: "WaningGibbous",
        Age: 21,
      },
      Temperature: {
        Minimum: {
          Value: 10.9,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 14.9,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 4.9,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 15.0,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 4.9,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 11.5,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      HoursOfSun: 5.7,
      DegreeDaySummary: {
        Heating: {
          Value: 5.0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 0.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 7,
          Category: "High",
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 14,
        IconPhrase: "Partly sunny w/ showers",
        HasPrecipitation: true,
        PrecipitationType: "Rain",
        PrecipitationIntensity: "Moderate",
        ShortPhrase: "A couple of morning showers",
        LongPhrase:
          "A couple of showers in the morning; otherwise, partly sunny and cool",
        PrecipitationProbability: 86,
        ThunderstormProbability: 17,
        RainProbability: 86,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 20.4,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 226,
            Localized: "SW",
            English: "SW",
          },
        },
        WindGust: {
          Speed: {
            Value: 40.7,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 238,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 4.5,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 4.5,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 2.0,
        HoursOfRain: 2.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 49,
        Evapotranspiration: {
          Value: 2.8,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 9555.5,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 18,
        IconPhrase: "Rain",
        HasPrecipitation: true,
        PrecipitationType: "Rain",
        PrecipitationIntensity: "Light",
        ShortPhrase: "Periods of rain",
        LongPhrase: "Periods of rain",
        PrecipitationProbability: 96,
        ThunderstormProbability: 8,
        RainProbability: 96,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 18.5,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 234,
            Localized: "SW",
            English: "SW",
          },
        },
        WindGust: {
          Speed: {
            Value: 40.7,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 260,
            Localized: "W",
            English: "W",
          },
        },
        TotalLiquid: {
          Value: 9.7,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 9.7,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 5.5,
        HoursOfRain: 5.5,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 86,
        Evapotranspiration: {
          Value: 0.8,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 10.3,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=2&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=2&unit=c&lang=en-us",
    },
    {
      Date: "2022-03-24T07:00:00+02:00",
      EpochDate: 1648098000,
      Sun: {
        Rise: "2022-03-24T05:40:00+02:00",
        EpochRise: 1648093200,
        Set: "2022-03-24T17:55:00+02:00",
        EpochSet: 1648137300,
      },
      Moon: {
        Rise: null,
        EpochRise: null,
        Set: "2022-03-24T09:47:00+02:00",
        EpochSet: 1648108020,
        Phase: "WaningGibbous",
        Age: 22,
      },
      Temperature: {
        Minimum: {
          Value: 10.5,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 14.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 6.0,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 11.8,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 6.0,
          Unit: "C",
          UnitType: 17,
          Phrase: "Chilly",
        },
        Maximum: {
          Value: 11.4,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      HoursOfSun: 2.6,
      DegreeDaySummary: {
        Heating: {
          Value: 6.0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 0.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 2,
          Category: "Low",
          CategoryValue: 1,
        },
      ],
      Day: {
        Icon: 18,
        IconPhrase: "Rain",
        HasPrecipitation: true,
        PrecipitationType: "Rain",
        PrecipitationIntensity: "Moderate",
        ShortPhrase: "Breezy with periods of rain",
        LongPhrase: "Breezy and cool with periods of rain",
        PrecipitationProbability: 95,
        ThunderstormProbability: 8,
        RainProbability: 95,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 24.1,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 261,
            Localized: "W",
            English: "W",
          },
        },
        WindGust: {
          Speed: {
            Value: 55.6,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 251,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 14.8,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 14.8,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 8.0,
        HoursOfRain: 8.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 86,
        Evapotranspiration: {
          Value: 1.8,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 5741.9,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 12,
        IconPhrase: "Showers",
        HasPrecipitation: true,
        PrecipitationType: "Rain",
        PrecipitationIntensity: "Moderate",
        ShortPhrase: "Early rain; mostly cloudy",
        LongPhrase: "Periods of rain in the evening; otherwise, mostly cloudy",
        PrecipitationProbability: 88,
        ThunderstormProbability: 0,
        RainProbability: 88,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 13.0,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 254,
            Localized: "WSW",
            English: "WSW",
          },
        },
        WindGust: {
          Speed: {
            Value: 29.6,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 244,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 12.4,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 12.4,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 4.0,
        HoursOfRain: 4.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 76,
        Evapotranspiration: {
          Value: 0.5,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 47.4,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=3&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=3&unit=c&lang=en-us",
    },
    {
      Date: "2022-03-25T07:00:00+02:00",
      EpochDate: 1648184400,
      Sun: {
        Rise: "2022-03-25T06:39:00+03:00",
        EpochRise: 1648179540,
        Set: "2022-03-25T18:56:00+03:00",
        EpochSet: 1648223760,
      },
      Moon: {
        Rise: "2022-03-25T01:47:00+03:00",
        EpochRise: 1648162020,
        Set: "2022-03-25T11:44:00+03:00",
        EpochSet: 1648197840,
        Phase: "Last",
        Age: 23,
      },
      Temperature: {
        Minimum: {
          Value: 12.4,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 15.2,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 11.7,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
        Maximum: {
          Value: 16.4,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 11.7,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
        Maximum: {
          Value: 13.3,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      HoursOfSun: 4.6,
      DegreeDaySummary: {
        Heating: {
          Value: 4.0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 0.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 6,
          Category: "High",
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 12,
        IconPhrase: "Showers",
        HasPrecipitation: true,
        PrecipitationType: "Rain",
        PrecipitationIntensity: "Light",
        ShortPhrase: "Occasional morning rain",
        LongPhrase: "A little morning rain; otherwise, mostly cloudy and cool",
        PrecipitationProbability: 59,
        ThunderstormProbability: 0,
        RainProbability: 59,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 14.8,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 293,
            Localized: "WNW",
            English: "WNW",
          },
        },
        WindGust: {
          Speed: {
            Value: 35.2,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 278,
            Localized: "W",
            English: "W",
          },
        },
        TotalLiquid: {
          Value: 1.5,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 1.5,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 1.0,
        HoursOfRain: 1.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 76,
        Evapotranspiration: {
          Value: 2.3,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 6887.6,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 34,
        IconPhrase: "Mostly clear",
        HasPrecipitation: false,
        ShortPhrase: "Clear to partly cloudy",
        LongPhrase: "Clear to partly cloudy",
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 187,
            Localized: "S",
            English: "S",
          },
        },
        WindGust: {
          Speed: {
            Value: 24.1,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 158,
            Localized: "SSE",
            English: "SSE",
          },
        },
        TotalLiquid: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 30,
        Evapotranspiration: {
          Value: 0.5,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 119.4,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=4&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=4&unit=c&lang=en-us",
    },
    {
      Date: "2022-03-26T07:00:00+02:00",
      EpochDate: 1648270800,
      Sun: {
        Rise: "2022-03-26T06:38:00+03:00",
        EpochRise: 1648265880,
        Set: "2022-03-26T18:56:00+03:00",
        EpochSet: 1648310160,
      },
      Moon: {
        Rise: "2022-03-26T02:49:00+03:00",
        EpochRise: 1648252140,
        Set: "2022-03-26T12:48:00+03:00",
        EpochSet: 1648288080,
        Phase: "WaningCrescent",
        Age: 24,
      },
      Temperature: {
        Minimum: {
          Value: 10.9,
          Unit: "C",
          UnitType: 17,
        },
        Maximum: {
          Value: 16.2,
          Unit: "C",
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 10.9,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
        Maximum: {
          Value: 19.5,
          Unit: "C",
          UnitType: 17,
          Phrase: "Pleasant",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 10.9,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
        Maximum: {
          Value: 14.5,
          Unit: "C",
          UnitType: 17,
          Phrase: "Cool",
        },
      },
      HoursOfSun: 9.5,
      DegreeDaySummary: {
        Heating: {
          Value: 4.0,
          Unit: "C",
          UnitType: 17,
        },
        Cooling: {
          Value: 0.0,
          Unit: "C",
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 7,
          Category: "High",
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 2,
        IconPhrase: "Mostly sunny",
        HasPrecipitation: false,
        ShortPhrase: "Mostly sunny and cool",
        LongPhrase: "Remaining cool with sunshine and a few clouds",
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 13.0,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 230,
            Localized: "SW",
            English: "SW",
          },
        },
        WindGust: {
          Speed: {
            Value: 37.0,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 240,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 21,
        Evapotranspiration: {
          Value: 3.3,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 12113.0,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: "Partly cloudy",
        HasPrecipitation: false,
        ShortPhrase: "Partly cloudy",
        LongPhrase: "Partly cloudy",
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 7.4,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 179,
            Localized: "S",
            English: "S",
          },
        },
        WindGust: {
          Speed: {
            Value: 20.4,
            Unit: "km/h",
            UnitType: 7,
          },
          Direction: {
            Degrees: 236,
            Localized: "SW",
            English: "SW",
          },
        },
        TotalLiquid: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Rain: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        Snow: {
          Value: 0.0,
          Unit: "cm",
          UnitType: 4,
        },
        Ice: {
          Value: 0.0,
          Unit: "mm",
          UnitType: 3,
        },
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 39,
        Evapotranspiration: {
          Value: 0.3,
          Unit: "mm",
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 105.9,
          Unit: "W/m²",
          UnitType: 33,
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=5&unit=c&lang=en-us",
      Link: "http://www.accuweather.com/en/il/tel-aviv/215854/daily-weather-forecast/215854?day=5&unit=c&lang=en-us",
    },
  ],
};

// http://dataservice.accuweather.com/forecasts/v1/daily/5day/215854?apikey=UKpjmRddsUSGtOhUGlrZNaSNLe3mTiNe&details=true&metric=true
