export default [
  {
    DateTime: "2022-03-23T00:00:00+02:00",
    EpochDateTime: 1647986400,
    WeatherIcon: 34,
    IconPhrase: "Mostly clear",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 9.3,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 9.3,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 4.8,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: -1.7,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 7.4,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 106,
        Localized: "ESE",
        English: "ESE",
      },
    },
    WindGust: {
      Speed: {
        Value: 16.7,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 45,
    IndoorRelativeHumidity: 38,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 10180.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 2,
    ThunderstormProbability: 0,
    RainProbability: 2,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 21,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=0&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=0&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T01:00:00+02:00",
    EpochDateTime: 1647990000,
    WeatherIcon: 34,
    IconPhrase: "Mostly clear",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 9.5,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 8.7,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 8.7,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 4.5,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: -2.3,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 7.4,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 144,
        Localized: "SE",
        English: "SE",
      },
    },
    WindGust: {
      Speed: {
        Value: 14.8,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 44,
    IndoorRelativeHumidity: 37,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 9144.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 6,
    ThunderstormProbability: 0,
    RainProbability: 6,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 27,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=1&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=1&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T02:00:00+02:00",
    EpochDateTime: 1647993600,
    WeatherIcon: 35,
    IconPhrase: "Partly cloudy",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 10.5,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 5.2,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: -1.5,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 9.3,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 158,
        Localized: "SSE",
        English: "SSE",
      },
    },
    WindGust: {
      Speed: {
        Value: 14.8,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 43,
    IndoorRelativeHumidity: 38,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 9144.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 6,
    ThunderstormProbability: 0,
    RainProbability: 6,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 34,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=2&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=2&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T03:00:00+02:00",
    EpochDateTime: 1647997200,
    WeatherIcon: 35,
    IconPhrase: "Partly cloudy",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 11.5,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 10.7,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    RealFeelTemperatureShade: {
      Value: 10.7,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    WetBulbTemperature: {
      Value: 6.0,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: -0.8,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 9.3,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 159,
        Localized: "SSE",
        English: "SSE",
      },
    },
    WindGust: {
      Speed: {
        Value: 16.7,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 42,
    IndoorRelativeHumidity: 39,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 9144.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 6,
    ThunderstormProbability: 0,
    RainProbability: 6,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 46,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=3&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=3&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T04:00:00+02:00",
    EpochDateTime: 1648000800,
    WeatherIcon: 36,
    IconPhrase: "Intermittent clouds",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 10.8,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 9.8,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 9.8,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 5.9,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: -0.1,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 9.3,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 156,
        Localized: "SSE",
        English: "SSE",
      },
    },
    WindGust: {
      Speed: {
        Value: 18.5,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 47,
    IndoorRelativeHumidity: 40,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 9144.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 5,
    ThunderstormProbability: 0,
    RainProbability: 5,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 59,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=4&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=4&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T05:00:00+02:00",
    EpochDateTime: 1648004400,
    WeatherIcon: 36,
    IconPhrase: "Intermittent clouds",
    HasPrecipitation: false,
    IsDaylight: false,
    Temperature: {
      Value: 10.2,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 8.9,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 8.9,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 5.9,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 0.7,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 9.3,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 155,
        Localized: "SSE",
        English: "SSE",
      },
    },
    WindGust: {
      Speed: {
        Value: 20.4,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 52,
    IndoorRelativeHumidity: 42,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 1951.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 5,
    ThunderstormProbability: 0,
    RainProbability: 5,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 71,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=5&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=5&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T06:00:00+02:00",
    EpochDateTime: 1648008000,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 10.9,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 6.6,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 1.7,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 9.3,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 162,
        Localized: "SSE",
        English: "SSE",
      },
    },
    WindGust: {
      Speed: {
        Value: 20.4,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 53,
    IndoorRelativeHumidity: 30,
    Visibility: {
      Value: 16.1,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 1006.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 8,
    ThunderstormProbability: 0,
    RainProbability: 8,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 79,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 0.0,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=6&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=6&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T07:00:00+02:00",
    EpochDateTime: 1648011600,
    WeatherIcon: 12,
    IconPhrase: "Showers",
    HasPrecipitation: true,
    PrecipitationType: "Rain",
    PrecipitationIntensity: "Moderate",
    IsDaylight: true,
    Temperature: {
      Value: 9.9,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 6.8,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 6.8,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 7.8,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 5.2,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 11.1,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 175,
        Localized: "S",
        English: "S",
      },
    },
    WindGust: {
      Speed: {
        Value: 20.4,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 73,
    IndoorRelativeHumidity: 38,
    Visibility: {
      Value: 8.0,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 792.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 73,
    ThunderstormProbability: 14,
    RainProbability: 73,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 2.3,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 2.3,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 86,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 224.3,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=7&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=7&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T08:00:00+02:00",
    EpochDateTime: 1648015200,
    WeatherIcon: 12,
    IconPhrase: "Showers",
    HasPrecipitation: true,
    PrecipitationType: "Rain",
    PrecipitationIntensity: "Moderate",
    IsDaylight: true,
    Temperature: {
      Value: 11.2,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 8.0,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    RealFeelTemperatureShade: {
      Value: 8.0,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 9.2,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 7.1,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 13.0,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 190,
        Localized: "S",
        English: "S",
      },
    },
    WindGust: {
      Speed: {
        Value: 20.4,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 76,
    IndoorRelativeHumidity: 43,
    Visibility: {
      Value: 8.0,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 579.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 73,
    ThunderstormProbability: 14,
    RainProbability: 73,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 2.3,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 2.3,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 93,
    Evapotranspiration: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 360.3,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=8&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=8&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T09:00:00+02:00",
    EpochDateTime: 1648018800,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 12.6,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 11.2,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    RealFeelTemperatureShade: {
      Value: 10.2,
      Unit: "C",
      UnitType: 17,
      Phrase: "Chilly",
    },
    WetBulbTemperature: {
      Value: 9.6,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 6.4,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 14.8,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 210,
        Localized: "SSW",
        English: "SSW",
      },
    },
    WindGust: {
      Speed: {
        Value: 24.1,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 66,
    IndoorRelativeHumidity: 41,
    Visibility: {
      Value: 9.7,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 579.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 49,
    ThunderstormProbability: 9,
    RainProbability: 49,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 86,
    Evapotranspiration: {
      Value: 0.3,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 553.4,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=9&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=9&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T10:00:00+02:00",
    EpochDateTime: 1648022400,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 13.6,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 12.3,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    RealFeelTemperatureShade: {
      Value: 10.7,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    WetBulbTemperature: {
      Value: 9.4,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 5.4,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 18.5,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 227,
        Localized: "SW",
        English: "SW",
      },
    },
    WindGust: {
      Speed: {
        Value: 29.6,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 58,
    IndoorRelativeHumidity: 38,
    Visibility: {
      Value: 9.7,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 1951.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 17,
    ThunderstormProbability: 3,
    RainProbability: 17,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 79,
    Evapotranspiration: {
      Value: 0.3,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 736.1,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=10&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=10&unit=c&lang=en-us",
  },
  {
    DateTime: "2022-03-23T11:00:00+02:00",
    EpochDateTime: 1648026000,
    WeatherIcon: 4,
    IconPhrase: "Intermittent clouds",
    HasPrecipitation: false,
    IsDaylight: true,
    Temperature: {
      Value: 14.2,
      Unit: "C",
      UnitType: 17,
    },
    RealFeelTemperature: {
      Value: 13.2,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    RealFeelTemperatureShade: {
      Value: 10.9,
      Unit: "C",
      UnitType: 17,
      Phrase: "Cool",
    },
    WetBulbTemperature: {
      Value: 9.0,
      Unit: "C",
      UnitType: 17,
    },
    DewPoint: {
      Value: 3.9,
      Unit: "C",
      UnitType: 17,
    },
    Wind: {
      Speed: {
        Value: 22.2,
        Unit: "km/h",
        UnitType: 7,
      },
      Direction: {
        Degrees: 235,
        Localized: "SW",
        English: "SW",
      },
    },
    WindGust: {
      Speed: {
        Value: 33.3,
        Unit: "km/h",
        UnitType: 7,
      },
    },
    RelativeHumidity: 50,
    IndoorRelativeHumidity: 35,
    Visibility: {
      Value: 8.0,
      Unit: "km",
      UnitType: 6,
    },
    Ceiling: {
      Value: 2987.0,
      Unit: "m",
      UnitType: 5,
    },
    UVIndex: 3,
    UVIndexText: "Moderate",
    PrecipitationProbability: 17,
    ThunderstormProbability: 3,
    RainProbability: 17,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Rain: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    Snow: {
      Value: 0.0,
      Unit: "cm",
      UnitType: 4,
    },
    Ice: {
      Value: 0.0,
      Unit: "mm",
      UnitType: 3,
    },
    CloudCover: 71,
    Evapotranspiration: {
      Value: 0.3,
      Unit: "mm",
      UnitType: 3,
    },
    SolarIrradiance: {
      Value: 906.2,
      Unit: "W/m²",
      UnitType: 33,
    },
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=11&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv/215854/hourly-weather-forecast/215854?day=2&hbhhour=11&unit=c&lang=en-us",
  },
];

//http://dataservice.accuweather.com/forecasts/v1/hourly/12hour/215854?apikey=UKpjmRddsUSGtOhUGlrZNaSNLe3mTiNe&details=true&metric=true
